config/routes.rb
IFOSSNews::Application.routes.draw do

  get "articles/admin"

  get "contact/index"

  get "faq/index"

  resources :articles

  root :to => 'articles#index'

  match '/admin' => 'articles#admin'

  match '/faqs' => 'faq#index'

  match '/contact' => 'contact#index'

  match '*path' => redirect('/')

end

app/models/article.rb
# encoding: utf-8

class Article < ActiveRecord::Base
  validates_presence_of :title, :body, :photothumb
  attr_accessible :body, :title, :photothumb

  has_attached_file :photothumb,
                    :styles => { :medium => "300x300>",
                                 :thumb => "100x100>" }

  def to_param
    title_short = title
    title_short = title_short.gsub(/[àáạảãâầấậẩẫăằắặẳẵÀÁẠẢÃĂẰẮẶẲẴÂẦẤẬẨẪ]/i,"a")
    title_short = title_short.gsub(/[èéẹẻẽêềếệểễÈÉẸẺẼÊỀẾỆỂỄ]/i,"e")
    title_short = title_short.gsub(/[ìíịỉĩÌÍỊỈĨ]/i,"i")
    title_short = title_short.gsub(/[òóọỏõôồốộổỗơờớợởỡÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠ]/i,"o")
    title_short = title_short.gsub(/[ùúụủũưừứựửữƯỪỨỰỬỮÙÚỤỦŨ]/i,"u")
    title_short = title_short.gsub(/[ỳýỵỷỹỲÝỴỶỸ]/i,"y")
    title_short = title_short.gsub(/[đĐ]/i,"d")
    title_short = title_short.gsub(/[^a-z0-9]+/i, '-')
    "#{id}-#{title_short}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 6).order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  # GET /articles/admin
  # GET /articles/admin
  def admin
    @articles = Article.paginate(:page => params[:page], :per_page => 6).order('created_at DESC')

    respond_to do |format|
      format.html # admin.html.erb
      format.json { render json: @articles }
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/views/articles/admin.html.erb
<% content_for :title, "Quản trị hệ thống" %>

<div class="span12">
  <%= link_to "Đăng tin mới",
              new_article_path,
              :class => 'btn btn-primary' %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Tiêu đề</th>
        <th>Thao tác</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to article.title, article_path(article) %></td>
          <td>
            <%= link_to "Sửa", edit_article_path(article),
                        :class => 'btn btn-mini' %>
            <%= link_to "Xóa", article_path(article),
                        :method => :delete,
                        :confirm => 'Bạn chắc chắn muốn xóa bài viết này',
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "Đăng tin mới",
              new_article_path,
              :class => 'btn btn-primary' %>

  <%= will_paginate @articles %>
</div>

app/views/articles/edit.html.erb
<% content_for :title,  "Sửa bài viết" %>
<h1>Sửa bài viết</h1>
<br />
<%= simple_form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.error_notification %>
    <%= f.input :title,
                :label => "Tiêu đề",
                :input_html => { :class => "span8" } %>

    <%= f.file_field :photothumb %>

    <%= f.input :body,
                :label => "Nội dung",
                :input_html => { :class => "span8" } %>

    <div class="form-actions">
      <%= f.submit "Cập nhật", :class => 'btn btn-primary' %>
      <%= link_to "Xóa", article_path,
                      :method => :delete,
                      :confirm => 'Bạn chắc chắn muốn xóa bài viết này',
                      :class => 'btn btn-danger' %>
      <%= link_to "Hủy", articles_path, :class => 'btn' %>
    </div>

<% end %>

app/views/articles/index.html.erb
<% content_for :title, "Trang chủ" %>

<div class="row">
  <% @articles.each do |article| %>
    <div class="span4">
      <h4><%= link_to truncate(article.title, :length => 45),
                      article_path(article) %></h4>
      <div class="thumbnail">
        <%= image_tag article.photothumb.url(:medium) %>
      </div>
      <p><%= truncate article.body, :length => 100 %></p>
    </div>
  <% end %>
</div>

<%= will_paginate @articles, :previous_label => '<<', :next_label => '>>' %>

app/views/articles/new.html.erb
<% content_for :title,  "Đăng tin mới" %>
<h1>Đăng tin mới</h1>
<br />

<%= simple_form_for @article,
                    :html => { :class => 'form-horizontal',
                               :multipart => true } do |f| %>
    <%= f.error_notification %>
    <%= f.input :title,
                :label => "Tiêu đề",
                :input_html => { :class => "span8" } %>

    <%= f.file_field :photothumb %>

    <%= f.input :body,
                :label => "Nội dung",
                :input_html => { :class => "span8" } %>

    <div class="form-actions">
      <%= f.submit "Đăng tin", :class => 'btn btn-primary' %>
      <%= link_to "Hủy", articles_path, :class => 'btn' %>
    </div>

<% end %>

app/views/articles/show.html.erb
<% content_for :title,  @article.title %>

<div class="span8" style="width:100%">
  <h4><%= @article.title %></h4>
    <div class="thumbnail" >
      <%= image_tag @article.photothumb.url(:medium) %>
    </div>

  <p><%=raw @article.body.bbcode_to_html %></p>

  <div class="form-actions">
    <%= link_to 'Quay lại', request.referer, :class => 'btn btn-primary'  %>
  </div>

</div>

app/views/contact/index.html.erb
<% content_for :title,  "Liên hệ" %>

<div id="mainwrap"><div id="main">
<div id="profile" class="w100">
<div id="personal" class="clearfix">
<div id="userpic"><img src="/MrTuxHdb.jpg" width="220" height="165" alt="MrTux"></div>
<h2 id="h2-name">MrTux</h2>
<ul class="nobullets">
<li>
<b>Age: </b> 28</li>
<li>
<b>Sex: </b> Male</li>
<li>
<b>Occupation:</b> Student of Water Resources University</li>
<li>
<b>Member since:</b> Dec 2008</li>
<li>
<b>Forum posts:</b> <a href="/community/forums/search.dml?username=mrtux-hdb&amp;exactusername=Y&amp;datemodifier=newer&amp;limitdate=any&amp;sortby=post&amp;disp=post&amp;ignorememberships=1">7</a>
</li>
<li>
<b>IRC</b> _Tux_@irc.freenode.net</li>
<li>
<b>Web site:</b> <a href="http://mrtux.yurx.com" rel="nofollow" class="overflow">http://mrtux.yurx.com</a>
</li>
</ul>
<div class="clear"></div>
</div>
<div class="col1" id="profile-col1"><div id="ff">
<h2>Fast facts</h2>
<ul class="nobullets">
<li>
<b>At the movies I like to see:</b>Phim hành động,phim giã sử,phim hài,phim VN ....</li>
<li>
<b>Last movie seen:</b>Shotter</li>
<li>
<b>Music I listen to:</b>Death/Black Metal, Rock, Nhạc không lời, ...</li>
<li>
<b>Best album right now:</b>Death - Symbolic 1995</li>
<li>
<b>Favorite author:</b>Chuck Schuldiner</li>
<li>
<b>Last book read:</b>Think Python</li>
<li>
<b>Best game right now:</b>Không chơi Game mới đau chứ !</li>
<li>
<b>Favorite sports team:</b>Võ thuật, Bóng đá, ...</li>
<li>
<b>I'm passionate about:</b>IT, OSS &amp; Linux</li>
<li>
<b>I wish I could:</b>Trở thành một chuyên gia CNTT. Con đường còn dài, nhưng vẫn ngày ngày cố gắng !</li>
<li>
<b>Favorite travel destination:</b>Đâu cũng được</li>
<li>
<b>On my vacation I..:</b>Nếu có bạn bè tủ rê thì đi tụ tập đàn đúm không thì ... ở nhà ôm em PC cả ngày !</li>
<li>
<b>If I won 1 million dollars, I would:</b>Nhiều tiền nhỉ ? Chắc là đi học vài khóa về Bảo mật và Lập trình viên.</li>
<li>
<b>If I were a super hero I would:</b>Cướp vợ ;))</li>
<li>
<b>I want my coffee..:</b>Đắng, càng đắng còn ngon : không đường, không đá, không sữa =&gt; Cafe nguyên chất mà dzọt</li>
<li>
<b>Food I like:</b>Thích nhiều lắm kể không hết</li>
<li>
<b>I don't like:</b>I'm not me !!!</li>
<li>
<b>Software I use:</b>OSS : Arch Linux, FF 3.5.5, OOO 3.1, xmms, mpd, GIMP ...</li>
<li>
<b>Hardware I use:</b>Main: ASUS P5K SE/EPU; CPU Intel Core2Duo E7200; HDD Seagate 160GB; VGA ASUS ATI Radeon HD 3650 ...</li>
<li>
<b>I discovered My Opera from:</b>Google ! Search Google vì thích Q&amp;S show vớ được Blog anh Lâm rồi cũng tự mình làm Blog và dùng cho đến giờ ! =&gt; Mởi chuyển nhà sang đây đấy chứ !!! Vì mình là SV rồi mà !!!</li>
</ul>
</div></div>
</div>

</div></div>

app/views/faq/index.html.erb
<% content_for :title,  "Hỏi đáp - FAQs" %>

<div class="span8" style="width:100%">
  <h4>Định nghĩa Mã nguồn mở</h4>
    <div class="thumbnail">
      <img alt="Gnu" src="/system/articles/photothumbs/000/000/040/medium/GNU.png?1337767143">
    </div>

  <p>Mã nguồn mở không chỉ có nghĩa là truy cập vào mã nguồn. Các điều khoản phân phối của phần mềm mã nguồn mở phải tuân thủ các tiêu chuẩn sau:<br>
<br>
1. Tự do tái phân phối<br>
Giấy phép đó sẽ không giới hạn bất cứ một bên nào khỏi việc bán hay đem cho phần mềm đó như là một thành phần của bản phân phối phần mềm tổng hợp mà có chứa các chương trình từ nhiều nguồn khác nhau. Giấy phép sẽ không đòi hỏi việc phải giữ nguyên trạng phần mềm hay các phí tổn khác cho những thương vụ như vậy.<br>
<br>
Lý do cơ bản: Bằng cách hạn chế giấy phép để yêu cầu phải cho phép tái phân phối tự do, chúng tôi giảm thiểu sức cám dỗ của việc từ bỏ những lợi ích dài hạn để tìm kiếm những đồng đô la bán sản phẩm tầm ngắn hạn. Nếu chúng tôi không làm vậy thì sẽ có rất nhiều áp lực khiến cho những người cùng tham gia cộng tác phải bỏ dở công việc phát triển.<br>
<br>
2. Mã nguồn<br>
<br>
Chương trình phải đi kèm mã nguồn, và phải cho phép phân phối cả mã nguồn cũng như dạng đã được biên dịch. Ở những nơi mà một số dạng sản phẩm không được phân phối cùng mã nguồn thì phải có các cách thức được phổ biến rộng rãi nhằm lấy được mã nguồn với chi phí không cao hơn chi phí tái sản xuất hợp lý–khuyến khích cho phép tải về một cách miễn phí qua Internet. Mã nguồn phải để dạng được ưa chuộng mà theo đó một lập trình viên sẽ có thể tham gia sửa đổi chương trình được. Việc biến đổi mã nguồn thành một dạng mã gây rối một cách có chủ tâm là không được phép. Những hình thức trung gian như kết quả xử lý từ một bộ tiền xử lý hay máy dịch cũng không được phép.<br>
<br>
Lý do cơ bản: Chúng tôi yêu cầu truy cập vào được thứ mã nguồn không phải là mã gây rối bởi vì bạn sẽ không thể làm cho chương trình phát triển khi không thay đổi chúng. Bởi vì mục đích của chúng tôi là tạo điều kiện để việc phát triển được thuận lợi nên chúng tôi yêu cầu sự sửa đổi mã nguồn cũng phải được tạo điều kiện thực hiện.<br>
<br>
3. Các chương trình phái sinh<br>
<br>
Giấy phép phải cho phép sửa đổi và các chương trình phái sinh từ đó, và phải cho phép chúng được phân phối dưới cùng các điều khoản như giấy phép của phần mềm gốc.<br>
<br>
Lý do cơ bản: Khả năng duy nhất là đọc mã nguồn là chưa đủ để hỗ trợ cho việc nghiên cứu, đánh giá có tính đồng đẳng độc lập cũng như việc lựa chọn nhanh mang mục đích phát triển thêm. Để việc phát triển sản phẩm diễn ra nhanh, mọi người cần được cung cấp khả năng làm việc để cho ra các bản sửa đổi và tái phân phối chúng.<br>
<br>
4. Tính toàn vẹn của mã nguồn cung cấp bởi Tác giả<br>
<br>
Giấy phép có thể hạn chế không cho phép mã nguồn được phân phối ở dạng đã được sửa đổi chỉ nếu như giấy phép cho phép phân phối “các file vá” cùng mã nguồn nhằm mục đích sửa đổi chương trình ở thời gian tạo sản phẩm. Giấy phép phải cho phép một cách tường minh việc phân phối phần mềm được tạo ra từ mã nguồn được sửa đổi. Giấy phép có thể yêu cầu các sản phẩm phái sinh phải mang một cái tên hay một số hiệu phiên bản khác so với phần mềm gốc.<br>
<br>
Lý do cơ bản: Việc khuyến khích có nhiều cải tiến là một điều tốt, nhưng những người sử dụng có quyền được biết ai chịu trách nhiệm về phần mềm mà họ đang sử dụng. Các tác giả và những người bảo trì có quyền lợi mang tính chất có đi có lại trong việc biết là họ đang được yêu cầu làm gì để hỗ trợ và bảo vệ danh tiếng về mặt uy tín của họ.<br>
<br>
Theo đó, một giấy phép mã nguồn mở phải đảm bảo rằng mã nguồn sẽ tồn tại ở dạng dễ dàng lấy được, nhưng có thể yêu cầu rằng nó sẽ được phân phối với cơ sở mã nguồn nguyên gốc ban đầu kèm với các bản vá. Theo cách này, những thay đổi “không chính thức” có thể xuất hiện ở hình thức sẵn sàng để tiếp cận nhưng được phân biệt một cách dễ dàng với mã nguồn cơ sở.<br>
<br>
5. Không có sự phân biệt đối xử giữa các cá nhân hay nhóm người<br>
<br>
Giấy phép phải không được phân biệt đối xử với bất cứ cá nhân hay nhóm người nào.<br>
<br>
Lý do cơ bản: Để thu được lợi ích tối đa từ quá trình này, thì giấy phép cũng phải tạo điều kiện để đạt được mức độ đa dạng tối đa của các cá nhân cũng như nhóm tham gia đóng góp vào mã nguồn. Do vậy chúng tôi không cho phép bất cứ một giấy phép mã nguồn mở nào ngăn cản bất cứ ai tham gia vào tiến trình.<br>
<br>
Một số quốc gia, trong đó có Hoa Kì, ban hành điều luật hạn chế xuất khẩu một số loại phần mềm nhất định. Một giấy phép tuân thủ Định nghĩa Mã Nguồn Mở có thể cảnh báo cho người sử dụng giấy phép về những hạn chế có thể được áp dụng và nhắc nhở họ là họ có nghĩa vụ tuân thủ luật pháp; tuy nhiên, giấy phép đó không được tự đặt ra các giới hạn như vậy.<br>
<br>
6. Không phân biệt đối xử với bất cứ một lĩnh vực công việc nào<br>
<br>
Giấy phép phải không được cản trở bất cứ ai khỏi việc sử dụng chương trình trong một lĩnh vực công việc cụ thể. Ví dụ, nó không được cản trở không cho chương trình đó được dùng trong một doanh nghiệp, hay không được dùng cho việc nghiên cứu gien.<br>
<br>
Lý do cơ bản: Lưu tâm chú yếu của điều khoản này là việc cấm các bẫy của giấy phép phục vụ cho việc cản trở mã nguồn mở không cho dùng trong các công việc có tính thương mại. Chúng tôi muốn những người sử dụng thương mại tham gia cộng đồng của chúng ta, chứ không phải cái cảm giác bị tách biệt khỏi nó.<br>
<br>
7. Việc phân phối giấy phép<br>
<br>
Các quyền lợi đi kèm với chương trình phải áp dụng cho tất cả những ai mà chương trình đó được tái phân phối đến đồng thời không cần phải thực thi một thứ giấy phép phụ thêm nào do các bên đó quy định. Lý do cơ bản: Điều khoản này là nhằm cấm đoán việc đóng phần mềm bằng cách cách thức gián tiếp như là yêu cầu một thỏa thuận ngầm.<br>
<br>
8. Giấy phép phải không được dành riêng cho một sản phẩm<br>
<br>
Các quyền lợi đi cùng chương trình đó phải không được phụ thuộc vào việc chương trình phải là một bộ phận một một bản phân phối phần mềm cụ thể. Nếu chương trình được tách ra từ bản phân phối đó và được sử dụng hay phân phối dưới các điều khoản của giấy phép kèm theo chương trình thì tất cả các bên mà chương trình được phân phối đến cũng nên có được các quyền lợi ngang bằng như những quyền lợi được đưa ra theo bản phân phối phần mềm gốc. Lý do cơ bản: Điều khoản này loại bỏ khả năng xảy ra các lớp bẫy giấy phép khác.<br>
<br>
9. Giấy phép phải không được cản trở các phần mềm khác<br>
<br>
Giấy phép phải không được áp đặt các giới hạn lên các phần mềm khác mà được phân phối kèm với phần mềm có giấy phép đó. Ví dụ, giấy phép không được chỉ dẫn nhất quyết rằng tất cả các phần mềm khác được phân phối trên cùng một phương tiện thì phải là phần mềm mã nguồn mở. Lý do cơ bản: Các nhà phân phối phần mềm mã nguồn mở phải có quyền đưa ra các lựa chọn của chính họ liên quan đến phần mềm của họ.<br>
<br>
Đúng là GPL tuân thủ theo yêu cầu này. Phần mềm liên kết với các thư viện phân phối dưới GPL chỉ kế thừa GPL nếu nó tạo nên một sản phẩm đơn nhất, chứ không phải là bất cứ phần mềm nào mà chúng chỉ được phân phối đi kèm theo.<br>
<br>
10. Giấy phép phải trung dung về mặt công nghệ<br>
<br>
Không cho phép tồn tại điều khoản nào của giấy phép khẳng định sự liên quan đến bất cứ một công nghệ riêng biệt hay một kiểu giao diện nào.<br>
<br>
Lý do cơ bản: Điều khoản này nhằm cụ thể vào các giấy phép mà đòi hỏi phải có một hành động thiện chí tường minh chứng tỏ sự chấp thuận nào để thiết lập một hợp đồng giữa người cấp giấy phép và người sử dụng giấy phép. Các điều khoản đặt dưới cái gọi là “kích chuột-kí kết”1 có thể xung đột với các phương thức phân phối phần mềm quan trọng như tải về qua FTP, tuyển phần mềm qua CD-ROM, và phân phối qua vùng web đồng dạng2; những điều khoản như vậy cũng có thể gây cản trở đến việc sử dụng lại mã. Các giấy phép tương thích phải cho phép (a) việc tái phân phối phần mềm sẽ diễn ra được trên các kênh không phải là web mà không hỗ trợ hình thức kích chuột-kí kết để tải về, và rằng (b) mã nguồn được bao gói (hay các phần được sử dụng lại của số mã nguồn được bao gói) có thể chạy trên một môi trường không có giao diện đồ họa người sử dụng mà có thể không hỗ trợ các hộp thoại popup.<br>
</p>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for(:title) || "iFOSSNews" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="/favicon.ico" type="image/x-icon" rel="shortcut icon">
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">iFOSSNews</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/"><i class="icon-home"></i>Trang chủ</a></li>
              <li><a href="/faqs"><i class="icon-question-sign"></i>FAQs</a></li>
              <li><a href="/contact"><i class="icon-envelope"></i>Liên hệ</a></li>
            </ul>
            <form class="navbar-search pull-left" action="/search">
              <input type="text" class="search-query span2" placeholder="Search">
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>

      <hr>

      <footer>
        <address>
          &copy; 2012<br />
          <abbr title="Sinh viên"><strong>Dương Tiến Thuận</strong></abbr><br />
          <abbr title="Lớp">50TH2</abbr><br />
          <abbr title="Trường">Đại Học Thủy Lợi Hà Nội</abbr><br />
          <abbr title="Địa chỉ">175 Tây Sơn, Đống Đa, Hà Nội</abbr><br />
        </address>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>